// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Logo: typeof import('./components/Logo.vue')['default']
    MdiFlash: typeof import('~icons/mdi/flash')['default']
    MdiHelp: typeof import('~icons/mdi/help')['default']
    MdiLock: typeof import('~icons/mdi/lock')['default']
    MdiMenu: typeof import('~icons/mdi/menu')['default']
    SharedSubtitle: typeof import('./components/SharedSubtitle.vue')['default']
  }
}
